-- 刪除商機對象的舊欄位定義
DELETE FROM fx_field_definitions WHERE object_api_name = 'NewOpportunityObj';

-- 插入商機對象的真實 CRM 欄位定義（基於實際 CRM 數據分析）
INSERT INTO fx_field_definitions 
  (object_api_name, field_api_name, field_label, field_type, field_description, is_required, created_at) 
  VALUES 
('NewOpportunityObj', '_id', '_id', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'account_id', 'account_id', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'account_id__r', 'account_id__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'account_id__relation_ids', 'account_id__relation_ids', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'amount', 'amount', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'close_date', 'close_date', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'cost_time', 'cost_time', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'create_time', 'create_time', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'created_by', 'created_by', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'created_by__l', 'created_by__l', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'created_by__r', 'created_by__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'currentStageIndex', 'currentStageIndex', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'data_own_department', 'data_own_department', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'data_own_department__l', 'data_own_department__l', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'data_own_department__r', 'data_own_department__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'extend_obj_data_id', 'extend_obj_data_id', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_30rKQ__c', 'field_30rKQ__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_3e2B2__c', 'field_3e2B2__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_5co25__c', 'field_5co25__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_Kt4Pg__c', 'field_Kt4Pg__c', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_Mrn1l__c', 'field_Mrn1l__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_SdEgv__c', 'field_SdEgv__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_UJ7fD__c', 'field_UJ7fD__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_UJ7fD__c__r', 'field_UJ7fD__c__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_bgi37__c', 'field_bgi37__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_e8m3q__c', 'field_e8m3q__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_hh49z__c', 'field_hh49z__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_i32Uj__c', 'field_i32Uj__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_lmjjf__c', 'field_lmjjf__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_lmjjf__c__r', 'field_lmjjf__c__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_mNxa4__c', 'field_mNxa4__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_nI1xS__c', 'field_nI1xS__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_rU4l5__c', 'field_rU4l5__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_vE1Zn__c', 'field_vE1Zn__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_zO24t__c', 'field_zO24t__c', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'field_zYRAu__c', 'field_zYRAu__c', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'is_deleted', 'is_deleted', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'last_followed_time', 'last_followed_time', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'last_modified_by', 'last_modified_by', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'last_modified_by__l', 'last_modified_by__l', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'last_modified_by__r', 'last_modified_by__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'last_modified_time', 'last_modified_time', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'leads_id', 'leads_id', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'leads_id__r', 'leads_id__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'leads_id__relation_ids', 'leads_id__relation_ids', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'life_status', 'life_status', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'life_status__r', 'life_status__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'lock_status', 'lock_status', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'lock_status__r', 'lock_status__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'lost_reason', 'lost_reason', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'lost_reason__o', 'lost_reason__o', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'lost_reason__r', 'lost_reason__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'name', 'name', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'new_opportunity_path', 'new_opportunity_path', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'opp_discount', 'opp_discount', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'opp_lines_sum', 'opp_lines_sum', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'owner', 'owner', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'owner__l', 'owner__l', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'owner__r', 'owner__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'owner_department', 'owner_department', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'owner_department_id', 'owner_department_id', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'probability', 'probability', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'probability_amount', 'probability_amount', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'record_type', 'record_type', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'relevant_team', 'relevant_team', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'relevant_team__r', 'relevant_team__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'sales_process_id', 'sales_process_id', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'sales_process_id__r', 'sales_process_id__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'sales_stage', 'sales_stage', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'sales_stage__r', 'sales_stage__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'sales_status', 'sales_status', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'sales_status__r', 'sales_status__r', 'TEXT', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'stg_changed_time', 'stg_changed_time', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'totalStageCount', 'totalStageCount', 'INTEGER', 'Real CRM field', 0, datetime('now')),
('NewOpportunityObj', 'version', 'version', 'TEXT', 'Real CRM field', 0, datetime('now'));

-- 注意：這裡不包含任何 field_l47x8__c (浴櫃價格) 或 field_8EBz1__c 等假欄位