
      INSERT INTO object_8w9cb__c (
        _id, name, owner, owner__r, owner_department_id, owner_department, create_time, created_by, created_by__r, last_modified_time, last_modified_by, last_modified_by__r, life_status, life_status__r, lock_status, lock_status__r, is_deleted, record_type, version, data_own_department, data_own_department__r, relevant_team, total_num, created_by__l, data_own_department__l, field_1P96q__c, field_1P96q__c__r, field_1P96q__c__relation_ids, field_23Z5i__c, field_23Z5i__c__r, field_B2gh1__c, field_Q6Svh__c, field_WD7k1__c, field_XuJP2__c, field_dxr31__c, field_dxr31__c__r, field_i2Q1g__c, field_k7e6q__c, field_k7e6q__c__r, field_k7e6q__c__relation_ids, field_npLvn__c, field_npLvn__c__r, field_npLvn__c__relation_ids, field_tXAko__c, last_modified_by__l, owner__l, relevant_team__r, searchAfterId, shift_time__c, shift_time__c__r, shift_time__c__relation_ids,
        fx_created_at, fx_updated_at, sync_version
      ) VALUES (
        '6874b50fd748ab000196001b', '25-07-14-3556', 'FSUID_303D4E189251A699407AA8A9F42B0D02', '楊凱中(已停用)', '1006', '業務二部', '1752478991527', 'FSUID_BDF4911AC3ADCD331A26BDD4550DB6C0', '楊佳玲', '1754641119220', '-10000', '系统', 'normal', '正常', '0', '未锁定', 'false', 'default__c', '7', '1006', '業務二部', '[{"teamMemberEmployee":["FSUID_303D4E189251A699407AA8A9F42B0D02"],"teamMemberType":"0","teamMemberRole":"1","teamMemberPermissionType":"2","teamMemberDeptCascade":"0"}]', '1', '[object Object]', '[object Object]', '651e2befd830ad00013cfcf7', '勝興-忠孝段-2024', '651e2befd830ad00013cfcf7', '6v4969CkY', '已完工', '19.70', '2.0', 'C', 'C5', 'option1', '工地', '0.00', '688c8e0d191a730001d4b0dd', '勝興-忠孝段-樣品層', '688c8e0d191a730001d4b0dd', '688c8f7d5450af00013c7fce', '勝興-忠孝段-樣品層-築愛家', '688c8f7d5450af00013c7fce', '19.70', '[object Object]', '[object Object]', '楊凱中(已停用)', '1754641119220,1754641119120182,6874b50fd748ab000196001b', '築愛家有限公司', '{"name":"築愛家有限公司","id":"66ff5c7270343b0001f80476"}', '66ff5c7270343b0001f80476',
        '1752478991527', '1754641119220', '0'
      )
      ON CONFLICT(_id) DO UPDATE SET
        name = excluded.name,
            owner = excluded.owner,
            owner__r = excluded.owner__r,
            owner_department_id = excluded.owner_department_id,
            owner_department = excluded.owner_department,
            last_modified_time = excluded.last_modified_time,
            last_modified_by = excluded.last_modified_by,
            last_modified_by__r = excluded.last_modified_by__r,
            life_status = excluded.life_status,
            life_status__r = excluded.life_status__r,
            lock_status = excluded.lock_status,
            lock_status__r = excluded.lock_status__r,
            is_deleted = excluded.is_deleted,
            record_type = excluded.record_type,
            version = excluded.version,
            data_own_department = excluded.data_own_department,
            data_own_department__r = excluded.data_own_department__r,
            relevant_team = excluded.relevant_team,
            total_num = excluded.total_num,
            created_by__l = excluded.created_by__l,
            data_own_department__l = excluded.data_own_department__l,
            field_1P96q__c = excluded.field_1P96q__c,
            field_1P96q__c__r = excluded.field_1P96q__c__r,
            field_1P96q__c__relation_ids = excluded.field_1P96q__c__relation_ids,
            field_23Z5i__c = excluded.field_23Z5i__c,
            field_23Z5i__c__r = excluded.field_23Z5i__c__r,
            field_B2gh1__c = excluded.field_B2gh1__c,
            field_Q6Svh__c = excluded.field_Q6Svh__c,
            field_WD7k1__c = excluded.field_WD7k1__c,
            field_XuJP2__c = excluded.field_XuJP2__c,
            field_dxr31__c = excluded.field_dxr31__c,
            field_dxr31__c__r = excluded.field_dxr31__c__r,
            field_i2Q1g__c = excluded.field_i2Q1g__c,
            field_k7e6q__c = excluded.field_k7e6q__c,
            field_k7e6q__c__r = excluded.field_k7e6q__c__r,
            field_k7e6q__c__relation_ids = excluded.field_k7e6q__c__relation_ids,
            field_npLvn__c = excluded.field_npLvn__c,
            field_npLvn__c__r = excluded.field_npLvn__c__r,
            field_npLvn__c__relation_ids = excluded.field_npLvn__c__relation_ids,
            field_tXAko__c = excluded.field_tXAko__c,
            last_modified_by__l = excluded.last_modified_by__l,
            owner__l = excluded.owner__l,
            relevant_team__r = excluded.relevant_team__r,
            searchAfterId = excluded.searchAfterId,
            shift_time__c = excluded.shift_time__c,
            shift_time__c__r = excluded.shift_time__c__r,
            shift_time__c__relation_ids = excluded.shift_time__c__relation_ids,
        fx_updated_at = excluded.fx_updated_at,
        sync_version = sync_version + 1,
        sync_time = CURRENT_TIMESTAMP
    