DELETE FROM fx_field_definitions WHERE object_api_name = 'NewOpportunityObj';

INSERT INTO fx_field_definitions 
      (object_api_name, field_api_name, field_label, field_type, field_description, is_required, created_at, data_source) 
      VALUES ('NewOpportunityObj', 'account_id__r', 'account_id__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'cost_time', 'cost_time', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'sales_stage__r', 'sales_stage__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'owner_department_id', 'owner_department_id', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'currentStageIndex', 'currentStageIndex', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'data_own_department__r', 'data_own_department__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'probability', 'probability', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'version', 'version', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_SdEgv__c', 'field_SdEgv__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'opp_discount', 'opp_discount', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'sales_process_id', 'sales_process_id', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'data_own_department__l', 'data_own_department__l', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_zO24t__c', 'field_zO24t__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_e8m3q__c', 'field_e8m3q__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'sales_status', 'sales_status', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'sales_stage', 'sales_stage', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'probability_amount', 'probability_amount', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'sales_process_id__r', 'sales_process_id__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'sales_status__r', 'sales_status__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'last_modified_time', 'last_modified_time', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'life_status', 'life_status', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_vE1Zn__c', 'field_vE1Zn__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'account_id', 'account_id', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'account_id__relation_ids', 'account_id__relation_ids', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'close_date', 'close_date', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'extend_obj_data_id', 'extend_obj_data_id', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'created_by__r', 'created_by__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'owner_department', 'owner_department', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'opp_lines_sum', 'opp_lines_sum', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'lock_status', 'lock_status', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'create_time', 'create_time', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'last_followed_time', 'last_followed_time', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'created_by', 'created_by', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_hh49z__c', 'field_hh49z__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'relevant_team', 'relevant_team', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'data_own_department', 'data_own_department', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_lmjjf__c', 'field_lmjjf__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'name', 'name', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', '_id', '_id', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_nI1xS__c', 'field_nI1xS__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'lock_status__r', 'lock_status__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'totalStageCount', 'totalStageCount', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'is_deleted', 'is_deleted', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'stg_changed_time', 'stg_changed_time', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'owner__l', 'owner__l', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_Mrn1l__c', 'field_Mrn1l__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'relevant_team__r', 'relevant_team__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'owner__r', 'owner__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'owner', 'owner', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'amount', 'amount', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_i32Uj__c', 'field_i32Uj__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'last_modified_by__l', 'last_modified_by__l', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'created_by__l', 'created_by__l', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_5co25__c', 'field_5co25__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'last_modified_by', 'last_modified_by', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'record_type', 'record_type', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'last_modified_by__r', 'last_modified_by__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'life_status__r', 'life_status__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_30rKQ__c', 'field_30rKQ__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_lmjjf__c__r', 'field_lmjjf__c__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_Kt4Pg__c', 'field_Kt4Pg__c', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_3e2B2__c', 'field_3e2B2__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_bgi37__c', 'field_bgi37__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_rU4l5__c', 'field_rU4l5__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_UJ7fD__c', 'field_UJ7fD__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_UJ7fD__c__r', 'field_UJ7fD__c__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_zYRAu__c', 'field_zYRAu__c', 'INTEGER', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'field_mNxa4__c', 'field_mNxa4__c', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'leads_id__r', 'leads_id__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'leads_id__relation_ids', 'leads_id__relation_ids', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'lost_reason__o', 'lost_reason__o', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'lost_reason__r', 'lost_reason__r', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'lost_reason', 'lost_reason', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'leads_id', 'leads_id', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM'),
('NewOpportunityObj', 'new_opportunity_path', 'new_opportunity_path', 'TEXT', 'Auto-generated from CRM data for 商機', 0, datetime('now'), 'CRM');

DELETE FROM fx_field_definitions WHERE object_api_name = 'SupplierObj';

INSERT INTO fx_field_definitions 
      (object_api_name, field_api_name, field_label, field_type, field_description, is_required, created_at, data_source) 
      VALUES ('SupplierObj', 'is_enable', 'is_enable', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'extend_obj_data_id', 'extend_obj_data_id', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'created_by__r', 'created_by__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'owner_department_id', 'owner_department_id', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'owner_department', 'owner_department', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'tel', 'tel', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'lock_status', 'lock_status', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'data_own_department__r', 'data_own_department__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'create_time', 'create_time', 'INTEGER', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'version', 'version', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'created_by', 'created_by', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'relevant_team', 'relevant_team', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'data_own_department', 'data_own_department', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'name', 'name', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', '_id', '_id', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'data_own_department__l', 'data_own_department__l', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'field_S4126__c__r', 'field_S4126__c__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'enterprise_registration', 'enterprise_registration', 'INTEGER', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'field_MK20f__c', 'field_MK20f__c', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'lock_status__r', 'lock_status__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'field_M42L8__c', 'field_M42L8__c', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'is_deleted', 'is_deleted', 'INTEGER', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'field_S4126__c', 'field_S4126__c', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'owner__l', 'owner__l', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'relevant_team__r', 'relevant_team__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'owner__r', 'owner__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'owner', 'owner', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'address', 'address', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'last_modified_time', 'last_modified_time', 'INTEGER', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'life_status', 'life_status', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'last_modified_by__l', 'last_modified_by__l', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'created_by__l', 'created_by__l', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'is_enable__r', 'is_enable__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'last_modified_by', 'last_modified_by', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'record_type', 'record_type', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'last_modified_by__r', 'last_modified_by__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'life_status__r', 'life_status__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'field_RNviK__c', 'field_RNviK__c', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'field_Vsk2n__c', 'field_Vsk2n__c', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'field_Ey2uR__c', 'field_Ey2uR__c', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'level', 'level', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'level__r', 'level__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'country', 'country', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'province', 'province', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'city__r', 'city__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'province__r', 'province__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'district', 'district', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'city', 'city', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'district__r', 'district__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'country__r', 'country__r', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM'),
('SupplierObj', 'email', 'email', 'TEXT', 'Auto-generated from CRM data for 供應商', 0, datetime('now'), 'CRM');

DELETE FROM fx_field_definitions WHERE object_api_name = 'object_8W9cb__c';

INSERT INTO fx_field_definitions 
      (object_api_name, field_api_name, field_label, field_type, field_description, is_required, created_at, data_source) 
      VALUES ('object_8W9cb__c', 'shift_time__c', 'shift_time__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'created_by__r', 'created_by__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'owner_department_id', 'owner_department_id', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'owner_department', 'owner_department', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_k7e6q__c__r', 'field_k7e6q__c__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'lock_status', 'lock_status', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'data_own_department__r', 'data_own_department__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'create_time', 'create_time', 'INTEGER', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_1P96q__c__r', 'field_1P96q__c__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_npLvn__c__relation_ids', 'field_npLvn__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'version', 'version', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'created_by', 'created_by', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'relevant_team', 'relevant_team', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'data_own_department', 'data_own_department', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_B2gh1__c', 'field_B2gh1__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'name', 'name', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_i2Q1g__c', 'field_i2Q1g__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', '_id', '_id', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'data_own_department__l', 'data_own_department__l', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_WD7k1__c', 'field_WD7k1__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_npLvn__c', 'field_npLvn__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_dxr31__c__r', 'field_dxr31__c__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'lock_status__r', 'lock_status__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'is_deleted', 'is_deleted', 'INTEGER', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'owner__l', 'owner__l', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_npLvn__c__r', 'field_npLvn__c__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'relevant_team__r', 'relevant_team__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'shift_time__c__v', 'shift_time__c__v', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_23Z5i__c__r', 'field_23Z5i__c__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'owner__r', 'owner__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'owner', 'owner', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_k7e6q__c__relation_ids', 'field_k7e6q__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'last_modified_time', 'last_modified_time', 'INTEGER', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'life_status', 'life_status', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'last_modified_by__l', 'last_modified_by__l', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'created_by__l', 'created_by__l', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_k7e6q__c', 'field_k7e6q__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'last_modified_by', 'last_modified_by', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_Q6Svh__c', 'field_Q6Svh__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'record_type', 'record_type', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'last_modified_by__r', 'last_modified_by__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_23Z5i__c', 'field_23Z5i__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_XuJP2__c', 'field_XuJP2__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'life_status__r', 'life_status__r', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_1P96q__c', 'field_1P96q__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_1P96q__c__relation_ids', 'field_1P96q__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_tXAko__c', 'field_tXAko__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_dxr31__c', 'field_dxr31__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'bad_case_scene__c', 'bad_case_scene__c', 'INTEGER', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'construction_completed__c', 'construction_completed__c', 'INTEGER', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM'),
('object_8W9cb__c', 'field_27g6n__c', 'field_27g6n__c', 'TEXT', 'Auto-generated from CRM data for 案場(SPC)', 0, datetime('now'), 'CRM');

DELETE FROM fx_field_definitions WHERE object_api_name = 'object_k1XqG__c';

INSERT INTO fx_field_definitions 
      (object_api_name, field_api_name, field_label, field_type, field_description, is_required, created_at, data_source) 
      VALUES ('object_k1XqG__c', 'created_by__r', 'created_by__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'life_status_before_invalid', 'life_status_before_invalid', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'owner_department_id', 'owner_department_id', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'owner_department', 'owner_department', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_SW6Eb__c', 'field_SW6Eb__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'building_type__c', 'building_type__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'lock_status', 'lock_status', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'data_own_department__r', 'data_own_department__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'create_time', 'create_time', 'INTEGER', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'version', 'version', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'created_by', 'created_by', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'relevant_team', 'relevant_team', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_Gm2wG__c', 'field_Gm2wG__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'data_own_department', 'data_own_department', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'name', 'name', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', '_id', '_id', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'data_own_department__l', 'data_own_department__l', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_7Aw8e__c', 'field_7Aw8e__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'location__c', 'location__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'lock_status__r', 'lock_status__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'is_deleted', 'is_deleted', 'INTEGER', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'owner__l', 'owner__l', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'relevant_team__r', 'relevant_team__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'owner__r', 'owner__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'owner', 'owner', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'last_modified_time', 'last_modified_time', 'INTEGER', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'life_status', 'life_status', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'last_modified_by__l', 'last_modified_by__l', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'created_by__l', 'created_by__l', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'last_modified_by', 'last_modified_by', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'record_type', 'record_type', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'last_modified_by__r', 'last_modified_by__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'life_status__r', 'life_status__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_87raN__c', 'field_87raN__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'shift_time__c', 'shift_time__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_sxZVc__c', 'field_sxZVc__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'property_site__c__r', 'property_site__c__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'photo__c', 'photo__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'property_site__c__relation_ids', 'property_site__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_sxZVc__c__r', 'field_sxZVc__c__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_g0vub__c', 'field_g0vub__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'shift_time__c__relation_ids', 'shift_time__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'property_site__c', 'property_site__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'work_shift_quotation_image__c', 'work_shift_quotation_image__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_sxZVc__c__relation_ids', 'field_sxZVc__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'movie__c', 'movie__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'area__c', 'area__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'shift_time__c__r', 'shift_time__c__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_repair_claim_form__c__r', 'field_repair_claim_form__c__r', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_repair_claim_form__c__relation_ids', 'field_repair_claim_form__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM'),
('object_k1XqG__c', 'field_repair_claim_form__c', 'field_repair_claim_form__c', 'TEXT', 'Auto-generated from CRM data for SPC維修單', 0, datetime('now'), 'CRM');

DELETE FROM fx_field_definitions WHERE object_api_name = 'site_cabinet__c';

INSERT INTO fx_field_definitions 
      (object_api_name, field_api_name, field_label, field_type, field_description, is_required, created_at, data_source) 
      VALUES ('site_cabinet__c', 'field_3T38o__c', 'field_3T38o__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_PuaLk__c', 'field_PuaLk__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'created_by__r', 'created_by__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_tyRfE__c', 'field_tyRfE__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'owner_department_id', 'owner_department_id', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'owner_department', 'owner_department', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'lock_status', 'lock_status', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'data_own_department__r', 'data_own_department__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'create_time', 'create_time', 'INTEGER', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_1P96q__c__r', 'field_1P96q__c__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_d2O5i__c', 'field_d2O5i__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_V3d91__c', 'field_V3d91__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'version', 'version', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'created_by', 'created_by', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'relevant_team', 'relevant_team', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_v1x3S__c', 'field_v1x3S__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'data_own_department', 'data_own_department', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'name', 'name', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', '_id', '_id', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'data_own_department__l', 'data_own_department__l', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_03U9h__c', 'field_03U9h__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_WD7k1__c', 'field_WD7k1__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'location__c', 'location__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_dxr31__c__r', 'field_dxr31__c__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'lock_status__r', 'lock_status__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'is_deleted', 'is_deleted', 'INTEGER', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_1zk34__c', 'field_1zk34__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'owner__l', 'owner__l', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'relevant_team__r', 'relevant_team__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_23Z5i__c__r', 'field_23Z5i__c__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'owner__r', 'owner__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'construction_completed__c', 'construction_completed__c', 'INTEGER', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'owner', 'owner', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_3Fqof__c', 'field_3Fqof__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'last_modified_time', 'last_modified_time', 'INTEGER', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'life_status', 'life_status', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'last_modified_by__l', 'last_modified_by__l', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'created_by__l', 'created_by__l', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'last_modified_by', 'last_modified_by', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_Q6Svh__c', 'field_Q6Svh__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'record_type', 'record_type', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'last_modified_by__r', 'last_modified_by__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_23Z5i__c', 'field_23Z5i__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_XuJP2__c', 'field_XuJP2__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'life_status__r', 'life_status__r', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_1P96q__c', 'field_1P96q__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_1P96q__c__relation_ids', 'field_1P96q__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_62279__c', 'field_62279__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM'),
('site_cabinet__c', 'field_dxr31__c', 'field_dxr31__c', 'TEXT', 'Auto-generated from CRM data for 案場(浴櫃)', 0, datetime('now'), 'CRM');

DELETE FROM fx_field_definitions WHERE object_api_name = 'progress_management_announ__c';

INSERT INTO fx_field_definitions 
      (object_api_name, field_api_name, field_label, field_type, field_description, is_required, created_at, data_source) 
      VALUES ('progress_management_announ__c', 'lock_status__r', 'lock_status__r', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'field_RFr42__c__relation_ids', 'field_RFr42__c__relation_ids', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'is_deleted', 'is_deleted', 'INTEGER', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'created_by__r', 'created_by__r', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'owner_department_id', 'owner_department_id', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'owner__l', 'owner__l', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'owner_department', 'owner_department', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'relevant_team__r', 'relevant_team__r', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'field_dvR88__c', 'field_dvR88__c', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'owner__r', 'owner__r', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'owner', 'owner', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'lock_status', 'lock_status', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'last_modified_time', 'last_modified_time', 'INTEGER', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'data_own_department__r', 'data_own_department__r', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'create_time', 'create_time', 'INTEGER', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'life_status', 'life_status', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'last_modified_by__l', 'last_modified_by__l', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'created_by__l', 'created_by__l', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'last_modified_by', 'last_modified_by', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'version', 'version', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'created_by', 'created_by', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'record_type', 'record_type', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'relevant_team', 'relevant_team', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'last_modified_by__r', 'last_modified_by__r', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'announcement_content__c', 'announcement_content__c', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'field_RFr42__c__r', 'field_RFr42__c__r', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'life_status__r', 'life_status__r', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'data_own_department', 'data_own_department', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'name', 'name', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'field_RFr42__c', 'field_RFr42__c', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', '_id', '_id', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM'),
('progress_management_announ__c', 'data_own_department__l', 'data_own_department__l', 'TEXT', 'Auto-generated from CRM data for 進度管理公告', 0, datetime('now'), 'CRM');