name = "fx-crm-sync"
main = "src/index.js"
compatibility_date = "2025-01-01"

# ========================================
# 基礎配置
# ========================================
[vars]
FX_API_BASE_URL = "https://open.fxiaoke.com"
SYNC_INTERVAL = "300000"
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "error"
SYNC_BATCH_SIZE = "200"
SYNC_MAX_BATCHES = "3"
ENABLE_AUTO_SYNC = "true"

# ========================================
# 生產環境資源
# ========================================
[[d1_databases]]
binding = "DB"
database_name = "fx-crm-database"
database_id = "332221d8-61cb-4084-88dc-394e208ae8b4"

[[kv_namespaces]]
binding = "KV"
id = "714f07950ac84f6ba8e00d3c961a6325"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "fx-crm-images"

[triggers]
# 自動同步：每小時執行一次增量同步以保持資料最新
crons = ["0 * * * *"]

# ========================================
# 兼容性設置
# ========================================
compatibility_flags = ["nodejs_compat"]

# ========================================
# 構建配置
# ========================================
[build]
command = "npm install"

# ========================================
# 上傳限制
# ========================================
# [limits]
# cpu_ms = 50  # 免費版不支援 CPU 限制

# ========================================
# 環境變數說明
# ========================================
# 敏感資訊請使用 wrangler secret put 命令設置：
# 
# 開發環境：
# wrangler secret put FX_APP_ID --env development
# wrangler secret put FX_APP_SECRET --env development
# wrangler secret put FX_PERMANENT_CODE --env development
# wrangler secret put JWT_SECRET --env development
# wrangler secret put API_TOKEN --env development
#
# 測試環境：
# wrangler secret put FX_APP_ID --env staging
# wrangler secret put FX_APP_SECRET --env staging
# wrangler secret put FX_PERMANENT_CODE --env staging
# wrangler secret put JWT_SECRET --env staging
# wrangler secret put API_TOKEN --env staging
#
# 生產環境：
# wrangler secret put FX_APP_ID --env production
# wrangler secret put FX_APP_SECRET --env production
# wrangler secret put FX_PERMANENT_CODE --env production
# wrangler secret put JWT_SECRET --env production
# wrangler secret put API_TOKEN --env production